version: "3.9"
services:
    db:
        image: postgres:13-alpine
        env_file:
            - .env.local
        container_name: db-dev
        ports: 
            - '5432:5432'
        volumes:
            - dbdata:/var/lib/postgresql/data/
            - ./dbscripts:/docker-entrypoint-initdb.d

    api:
        image: yzia2000/zims-classroom:dev
        env_file:
            - .env.local
        build:
            context: .
            target: base
        container_name: api-dev
        command: npm run dev
        volumes:
            - ./src:/app/src
            - ./package.json:/app/package.json
        depends_on:
            - db
        ports:
            - '5000:5000'
        profiles: ['dev']

    api-test:
        image: yzia2000/zims-classroom:test
        env_file:
            - .env.local
        environment:
            - NODE_ENV=test
        build:
            context: .
            target: builder
        container_name: api-test
        command: ./wait-for-it.sh db:5432 -- /bin/sh -c "npm run test"
        depends_on:
            - db
        ports:
            - '5000:5000'
        profiles: ['test']

    api-prod:
        image: yzia2000/zims-classroom:latest
        environment:
            - NODE_ENV=production
            - POSTGRES_PASSWORD
            - POSTGRES_USER
            - POSTGRES_DB
            - JWT_SECRET
        build:
            context: .
        container_name: api
        depends_on:
            - db
        ports:
            - '5000:5000'
        profiles: ['prod']

volumes:
    dbdata:
